### ISSUE TITLE
no proper documentation 

### ISSUE THREAD

**Issue by Zumbalamambo** [smartcat-labs/facelyzr#34]
How do i run this code?

**Comment by StankoKuveljic** [comment]
Hello, 
Everything is in pieces right now. This project is my master thesis, and I will continue to work on it soon.
There is one example that I used for pretraing stacked denosing autoencoder: 
https://github.com/smartcat-labs/facelyzr/blob/dev/networks/optimization/pretrain/stacked_DAE.py
This is just the pretraining part, I've done some experiments with supervised fine tuning using that pretrained model for predicting age/gender and other facial attributes from Celeba dataset, even the results were great, code is not ready yet. First I need to fix some stuff.
I need to wire all this code, do some refactoring and bug fixing, export/import of TF model as protobuf, add rest API, etc.
After that I'll plan to make some examples in jupyter notebook to show how it all works.
Thanks.
